// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickets.Api.Data.EntityFramework;

namespace Tickets.Api.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181205123811_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tickets.Api.Data.Entities.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("BoardGuid");

                    b.Property<Guid>("CompanyGuid");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("CreationUserGuid");

                    b.Property<bool?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime?>("LastUpdateTime");

                    b.Property<Guid?>("LastUpdateUserGuid");

                    b.Property<Guid>("StatusGuid");

                    b.Property<string>("Summary");

                    b.Property<Guid>("UserGuid");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new { TicketId = 1L, BoardGuid = new Guid("c131073d-cbd5-4b26-bbda-99eda8392a46"), CompanyGuid = new Guid("22e44764-3f21-471f-8f18-ae43d613c8cd"), CreationTime = new DateTime(2018, 12, 5, 12, 38, 11, 151, DateTimeKind.Local), CreationUserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff"), Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis massa eu lorem rutrum scelerisque. Aliquam quis faucibus dui. Morbi eu diam condimentum, aliquet lorem eget, convallis augue. Nam a nisi at est elementum dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in magna ac mauris eleifend imperdiet sit amet in purus. Phasellus eu mi arcu. Etiam a tempus lectus. In hac habitasse platea dictumst. Fusce viverra sed metus id pretium. Proin auctor enim eu massa fringilla, at vestibulum lacus egestas.

In hac habitasse platea dictumst. Phasellus non semper nisi. Proin consequat, ante et pretium imperdiet, velit augue congue leo, consectetur euismod turpis tellus nec felis. Quisque tempor id libero et maximus. In ullamcorper dolor leo, quis tempus sapien auctor id. Sed eget augue vel augue accumsan ornare. Aliquam ac felis a elit bibendum malesuada at eget arcu. Mauris id tempus lacus. Aenean volutpat tristique sem quis interdum. Cras eu eros at lorem tincidunt pharetra vel ac tortor. Donec non suscipit arcu. Maecenas luctus, eros sodales iaculis feugiat, nisl massa venenatis velit, ullamcorper vulputate quam nisi a dui. Aenean posuere, risus quis lobortis dictum, nisi erat mattis odio, eu porttitor massa neque vel ligula. Mauris et pretium justo, id gravida neque.", Guid = new Guid("e5a1cd26-a799-4ddf-86ab-0c425a2bd4d4"), StatusGuid = new Guid("0ad8d818-cea5-4401-a851-614f37133ed1"), Summary = "Ticket number 1", UserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff") },
                        new { TicketId = 2L, BoardGuid = new Guid("c131073d-cbd5-4b26-bbda-99eda8392a46"), CompanyGuid = new Guid("22e44764-3f21-471f-8f18-ae43d613c8cd"), CreationTime = new DateTime(2018, 12, 5, 12, 38, 11, 153, DateTimeKind.Local), CreationUserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff"), Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis massa eu lorem rutrum scelerisque. Aliquam quis faucibus dui. Morbi eu diam condimentum, aliquet lorem eget, convallis augue. Nam a nisi at est elementum dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in magna ac mauris eleifend imperdiet sit amet in purus. Phasellus eu mi arcu. Etiam a tempus lectus. In hac habitasse platea dictumst. Fusce viverra sed metus id pretium. Proin auctor enim eu massa fringilla, at vestibulum lacus egestas.

In hac habitasse platea dictumst. Phasellus non semper nisi. Proin consequat, ante et pretium imperdiet, velit augue congue leo, consectetur euismod turpis tellus nec felis. Quisque tempor id libero et maximus. In ullamcorper dolor leo, quis tempus sapien auctor id. Sed eget augue vel augue accumsan ornare. Aliquam ac felis a elit bibendum malesuada at eget arcu. Mauris id tempus lacus. Aenean volutpat tristique sem quis interdum. Cras eu eros at lorem tincidunt pharetra vel ac tortor. Donec non suscipit arcu. Maecenas luctus, eros sodales iaculis feugiat, nisl massa venenatis velit, ullamcorper vulputate quam nisi a dui. Aenean posuere, risus quis lobortis dictum, nisi erat mattis odio, eu porttitor massa neque vel ligula. Mauris et pretium justo, id gravida neque.", Guid = new Guid("8a81bd0f-5458-4493-b82f-feae8b650a57"), StatusGuid = new Guid("0ad8d818-cea5-4401-a851-614f37133ed1"), Summary = "Ticket number 2", UserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff") },
                        new { TicketId = 3L, BoardGuid = new Guid("48c85d34-1345-4363-93b7-f2d2785bf07e"), CompanyGuid = new Guid("3272d072-ac00-4d3a-8d3a-40a14d8d789d"), CreationTime = new DateTime(2018, 12, 5, 12, 38, 11, 153, DateTimeKind.Local), CreationUserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff"), Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis massa eu lorem rutrum scelerisque. Aliquam quis faucibus dui. Morbi eu diam condimentum, aliquet lorem eget, convallis augue. Nam a nisi at est elementum dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in magna ac mauris eleifend imperdiet sit amet in purus. Phasellus eu mi arcu. Etiam a tempus lectus. In hac habitasse platea dictumst. Fusce viverra sed metus id pretium. Proin auctor enim eu massa fringilla, at vestibulum lacus egestas.

In hac habitasse platea dictumst. Phasellus non semper nisi. Proin consequat, ante et pretium imperdiet, velit augue congue leo, consectetur euismod turpis tellus nec felis. Quisque tempor id libero et maximus. In ullamcorper dolor leo, quis tempus sapien auctor id. Sed eget augue vel augue accumsan ornare. Aliquam ac felis a elit bibendum malesuada at eget arcu. Mauris id tempus lacus. Aenean volutpat tristique sem quis interdum. Cras eu eros at lorem tincidunt pharetra vel ac tortor. Donec non suscipit arcu. Maecenas luctus, eros sodales iaculis feugiat, nisl massa venenatis velit, ullamcorper vulputate quam nisi a dui. Aenean posuere, risus quis lobortis dictum, nisi erat mattis odio, eu porttitor massa neque vel ligula. Mauris et pretium justo, id gravida neque.", Guid = new Guid("afe42e10-02ce-4c2c-a3e5-81c68ca0f95c"), StatusGuid = new Guid("0ad8d818-cea5-4401-a851-614f37133ed9"), Summary = "Ticket number 3", UserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff") },
                        new { TicketId = 4L, BoardGuid = new Guid("48c85d34-1345-4363-93b7-f2d2785bf07e"), CompanyGuid = new Guid("3272d072-ac00-4d3a-8d3a-40a14d8d789d"), CreationTime = new DateTime(2018, 12, 5, 12, 38, 11, 153, DateTimeKind.Local), CreationUserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff"), Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis massa eu lorem rutrum scelerisque. Aliquam quis faucibus dui. Morbi eu diam condimentum, aliquet lorem eget, convallis augue. Nam a nisi at est elementum dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in magna ac mauris eleifend imperdiet sit amet in purus. Phasellus eu mi arcu. Etiam a tempus lectus. In hac habitasse platea dictumst. Fusce viverra sed metus id pretium. Proin auctor enim eu massa fringilla, at vestibulum lacus egestas.

In hac habitasse platea dictumst. Phasellus non semper nisi. Proin consequat, ante et pretium imperdiet, velit augue congue leo, consectetur euismod turpis tellus nec felis. Quisque tempor id libero et maximus. In ullamcorper dolor leo, quis tempus sapien auctor id. Sed eget augue vel augue accumsan ornare. Aliquam ac felis a elit bibendum malesuada at eget arcu. Mauris id tempus lacus. Aenean volutpat tristique sem quis interdum. Cras eu eros at lorem tincidunt pharetra vel ac tortor. Donec non suscipit arcu. Maecenas luctus, eros sodales iaculis feugiat, nisl massa venenatis velit, ullamcorper vulputate quam nisi a dui. Aenean posuere, risus quis lobortis dictum, nisi erat mattis odio, eu porttitor massa neque vel ligula. Mauris et pretium justo, id gravida neque.", Guid = new Guid("e22b8d3c-5f9b-4cd8-b419-872924c6c8b0"), StatusGuid = new Guid("0ad8d818-cea5-4401-a851-614f37133ed1"), Summary = "Ticket number 4", UserGuid = new Guid("d3a9dece-b96d-457c-8b86-273b72e37cff") }
                    );
                });

            modelBuilder.Entity("Tickets.Api.Data.Entities.TicketMember", b =>
                {
                    b.Property<long>("TicketMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CompanyGuid");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("CreationUserGuid");

                    b.Property<bool?>("Deleted");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime?>("LastUpdateTime");

                    b.Property<Guid?>("LastUpdateUserGuid");

                    b.Property<Guid>("TeamUserGuid");

                    b.Property<Guid>("TicketGuid");

                    b.Property<Guid>("UserGuid");

                    b.HasKey("TicketMemberId");

                    b.ToTable("TicketMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
