// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Email.Business.AutoRrest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class JwtModel
    {
        /// <summary>
        /// Initializes a new instance of the JwtModel class.
        /// </summary>
        public JwtModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JwtModel class.
        /// </summary>
        public JwtModel(string tokenString = default(string))
        {
            TokenString = tokenString;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenString")]
        public string TokenString { get; set; }

    }
}
