// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Email.Business.AutoRrest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TeamUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the TeamUserRequest class.
        /// </summary>
        public TeamUserRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TeamUserRequest class.
        /// </summary>
        public TeamUserRequest(System.Guid? userGuid = default(System.Guid?), System.Guid? teamGuid = default(System.Guid?))
        {
            UserGuid = userGuid;
            TeamGuid = teamGuid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userGuid")]
        public System.Guid? UserGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teamGuid")]
        public System.Guid? TeamGuid { get; set; }

    }
}
