// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Email.Business.AutoRrest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TeamUserSearchResponse
    {
        /// <summary>
        /// Initializes a new instance of the TeamUserSearchResponse class.
        /// </summary>
        public TeamUserSearchResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TeamUserSearchResponse class.
        /// </summary>
        public TeamUserSearchResponse(IList<TeamUserResponse> data = default(IList<TeamUserResponse>))
        {
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<TeamUserResponse> Data { get; set; }

    }
}
