// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Email.Business.AutoRrest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TeamResponse
    {
        /// <summary>
        /// Initializes a new instance of the TeamResponse class.
        /// </summary>
        public TeamResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TeamResponse class.
        /// </summary>
        public TeamResponse(System.Guid? guid = default(System.Guid?), System.DateTime? creationTime = default(System.DateTime?), string name = default(string))
        {
            Guid = guid;
            CreationTime = creationTime;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creationTime")]
        public System.DateTime? CreationTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
