// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Email.Business.AutoRrest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserModel
    {
        /// <summary>
        /// Initializes a new instance of the UserModel class.
        /// </summary>
        public UserModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserModel class.
        /// </summary>
        public UserModel(string id = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), System.Guid? companyGuid = default(System.Guid?), string avatar = default(string))
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            CompanyGuid = companyGuid;
            Avatar = avatar;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companyGuid")]
        public System.Guid? CompanyGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "avatar")]
        public string Avatar { get; set; }

    }
}
